# Data Discovery in Data Lakes with BLEND

### Load libraries and define paths

In [1]:
import os
import sys
from pathlib import Path
import polars as pl
from tabulate import tabulate

In [2]:
sys.path.append(
    str(Path(os.path.abspath(os.path.curdir)).parent.absolute())
)


from blend import BLEND
from blend.indexing import index_tables

In [3]:
data_path = Path(os.path.abspath(os.path.curdir)).parent.joinpath("examples", "example-data", "modena")

data_lake_path = data_path.joinpath("data-lake")
index_db_path = data_path.joinpath("modena.db")
logdir_path = data_path.joinpath("log")
queries_path = data_path.joinpath("queries")

data_path.exists()

True

### Instantiate BLEND index

In [4]:
indexer = BLEND(index_db_path, clean_args={"lowercase": True})

In [5]:
load_opts = {"ignore_errors": True}
# index_tables(indexer, data_lake_path, True, None, 4, load_opts)

### Load the query dataset

We have some datasets in the _query_ folder:

In [6]:
queries = sorted(os.listdir(queries_path))

print('\n\n'.join(queries))

Archi-stradali.csv

Risultati-di-lista-delle-elezioni-europee-del-2024.cpy-0.csv

ds115_economia_spesa_media_mese_categoria_area_residenza_2007-2013.csv

section_district_codes.csv

In [7]:
# select one of the available queries
query_table_idx = 1
query_table_name = queries[query_table_idx]

# load the query dataset
qdf = pl.read_csv(queries_path.joinpath(query_table_name))

qdf

shape: (152, 27)
┌──────────────────┬─────────┬──────────────┬─────────────┬───┬────────┬──────┬────────────┬───────┐
│ THE_PK_KEY       ┆ SECTION ┆ DISTRICT     ┆ DISTRICT_CD ┆ … ┆ #VALID ┆ FORM ┆ #NOT VALID ┆ #NULL │
│ ---              ┆ ---     ┆ ---          ┆ ---         ┆   ┆ ---    ┆ ---  ┆ ---        ┆ ---   │
│ str              ┆ i64     ┆ str          ┆ i64         ┆   ┆ i64    ┆ str  ┆ i64        ┆ i64   │
╞══════════════════╪═════════╪══════════════╪═════════════╪═══╪════════╪══════╪════════════╪═══════╡
│ 1_Centro_Europee ┆ 1       ┆ Centro       ┆ 1           ┆ … ┆ 525    ┆ E24  ┆ 8          ┆ 2     │
│ 2_Centro_Europee ┆ 2       ┆ Centro       ┆ 1           ┆ … ┆ 431    ┆ E24  ┆ 13         ┆ 10    │
│ null             ┆ 5       ┆ Centro       ┆ 1           ┆ … ┆ 505    ┆ E24  ┆ 7          ┆ 4     │
│ 7_Centro_Europee ┆ 7       ┆ Centro       ┆ 1           ┆ … ┆ 584    ┆ E24  ┆ 12         ┆ 8     │
│ 8_Centro_Europee ┆ 8       ┆ Centro       ┆ 1           ┆ … ┆ 392    ┆ E24  ┆ 6          ┆ 2     │
│ …                ┆ …       ┆ …            ┆ …           ┆ … ┆ …      ┆ …    ┆ …          ┆ …     │
│ null             ┆ 185     ┆ San Faustino ┆ null        ┆ … ┆ 609    ┆ E24  ┆ 9          ┆ 4     │
│ 187_Buon         ┆ 187     ┆ Buon Pastore ┆ 3           ┆ … ┆ 420    ┆ E24  ┆ 6          ┆ 3     │
│ Pastore_Europee  ┆         ┆              ┆             ┆   ┆        ┆      ┆            ┆       │
│ 188_Buon         ┆ 188     ┆ Buon Pastore ┆ 3           ┆ … ┆ 502    ┆ E24  ┆ 19         ┆ 14    │
│ Pastore_Europee  ┆         ┆              ┆             ┆   ┆        ┆      ┆            ┆       │
│ 189_Buon         ┆ 189     ┆ Buon Pastore ┆ 3           ┆ … ┆ 520    ┆ E24  ┆ 14         ┆ 3     │
│ Pastore_Europee  ┆         ┆              ┆             ┆   ┆        ┆      ┆            ┆       │
│ 190_San          ┆ 190     ┆ San Faustino ┆ 4           ┆ … ┆ 482    ┆ E24  ┆ 15         ┆ 9     │
│ Faustino_Europee ┆         ┆              ┆             ┆   ┆        ┆      ┆            ┆       │
└──────────────────┴─────────┴──────────────┴─────────────┴───┴────────┴──────┴────────────┴───────┘

## Keyword Search

In many use-cases, one of the simplest and most useful kind of data discovery task is the _keyword_ search.

Basically, we want to identify those datasets whose cell values, considered as a set, have the highest overlap with a user-given query set.

We don't check for any ordering on rows/columns, just the overlap.

In [8]:
# we flatten our query dataframe values to a set
# values = list(set(map(clean, {cell for row in qdf.rows() for cell in row})))
values = list({cell for row in qdf.rows() for cell in row})
len(values)

668

In [9]:
results = indexer.keyword_search(values, k=20)

print(f"Query table: {query_table_name}\n")

print(tabulate(results, headers=['dataset', 'overlap']))

Query table: Risultati-di-lista-delle-elezioni-europee-del-2024.cpy-0.csv

dataset                                                         overlap
------------------------------------------------------------  ---------
Risultati-di-lista-delle-elezioni-europee-del-2024                  667
Risultati-di-lista-delle-elezioni-europee-del-2024.cpy-0            667
Stradario-comunale                                                  536
Archi-stradali                                                      536
Sezioni-di-censimento                                               531
Pratiche-edilizie-anni-dal-1900-al-1999                             531
Pratiche-edilizie-anni-dal-2000-ad-oggi                             531
Servizio-di-scarico-risorsa-in-formato-CSV                          530
Risultati-delle-elezioni-europee-2019                               529
File-in-formato-csv                                                 519
Risultati-delle-elezioni-europee-anno-2014                          516
Risultati-delle-elezioni-europee-2009                               516
Famiglie-aggregate-per-numero-di-componenti-la-famiglia             511
Famiglie-residenti-suddivise-per-zone-urbanistiche                  508
Risultati-delle-elezioni-europee-2019.cpy-0                         473
Risultati-delle-elezioni-europee-2019.cpy-1                         470
Affluenze-e-risultati-elettorali-delle-elezioni-europee-2024        454
Affluenze-delle-elezioni-europee-2019                               451
Affluenze-delle-elezioni-europee-2009                               449
Affluenze-delle-elezioni-europee-2014                               449

## Unionable Table Search

In [14]:
table = qdf.rows()
results = indexer.union_search(table, 10)

print(f"Query table: {query_table_name}\n")
print(tabulate(results, headers=['dataset']))

Query table: Risultati-di-lista-delle-elezioni-europee-del-2024.cpy-0.csv

dataset
---------------------------------------------------------
File-in-formato-csv
Archi-stradali
Risultati-delle-elezioni-europee-2019
Risultati-di-lista-delle-elezioni-regionali-del-2024
Risultati-di-lista-delle-elezioni-europee-del-2024
Risultati-di-lista-delle-elezioni-amministrative-del-2009
Risultati-di-lista-delle-elezioni-amministrative-del-2014
Stradario-comunale
Risultati-di-lista-delle-elezioni-amministrative-del-2024
Risultati-di-lista-delle-elezioni-amministrative-del-2019

## Single Column JOIN Search

The dataset above has a single key column, _THE\_KEY_, which is the combination of _SECTION_, _DISTRICT\_CD_ and _ELECTION_

Such a combination might be useful to retrieve related tables using BLEND.

In [12]:
# extract and clean the values of the key
# column = qdf.get_column('THE_PK_KEY').map_elements(lambda x: clean(x), pl.String).drop_nulls()

column = qdf.get_column('THE_PK_KEY').drop_nulls().to_list()
column[:5]

['1_Centro_Europee',
 '2_Centro_Europee',
 '7_Centro_Europee',
 '8_Centro_Europee',
 '9_Centro_Europee']

Execute the search with BLEND, returning the 10 columns with highest overlap with the query. If we run the query several times with the same input, we 
should see always the same results (ties may appear in different order).

In [14]:
results = indexer.single_column_join_search(column, k=20)

print(f"Query table: {query_table_name}\n")
print(tabulate(results, headers=['dataset', 'column idx', 'overlap (distinct)', 'overlap (general)']))

Query table: Risultati-di-lista-delle-elezioni-europee-del-2024.cpy-0.csv

dataset                                                               column idx    overlap (distinct)
------------------------------------------------------------------  ------------  --------------------
Risultati-di-lista-delle-elezioni-europee-del-2024                             0                   128
Risultati-delle-elezioni-europee-2019                                          0                   128
Risultati-di-lista-delle-elezioni-europee-del-2024.cpy-0                       0                   128
Affluenze-delle-elezioni-europee-2019                                          0                   128
Affluenze-e-risultati-elettorali-delle-elezioni-europee-2024                   0                   128
Affluenze-delle-elezioni-europee-2009                                          0                   125
Risultati-delle-elezioni-europee-2009                                          0                   125
Risultati-delle-elezioni-europee-anno-2014                                     0                   125
Affluenze-delle-elezioni-europee-2014                                          0                   125
Risultati-delle-elezioni-europee-2019.cpy-0                                    0                   104
Risultati-delle-elezioni-europee-2019.cpy-1                                    0                   104
Affluenze-e-risultati-elettorali-delle-elezioni-europee-2024.cpy-0             0                   100
Affluenze-delle-elezioni-europee-2019.cpy-0                                    0                    94
Risultati-delle-elezioni-europee-anno-2014.cpy-0                               0                    85
Risultati-delle-elezioni-europee-2009.cpy-0                                    0                    84
Risultati-delle-elezioni-europee-anno-2014.cpy-1                               0                    83
Risultati-delle-elezioni-europee-2009.cpy-1                                    0                    77
Affluenze-delle-elezioni-europee-2019.cpy-1                                    0                    73

We can now easily identify the datasets we are most interested with; we can load them by accessing the results list and check
their content.

In [15]:
r_df = pl.read_csv(data_lake_path.joinpath(f"{results[-1][0]}.csv"))
r_df

shape: (152, 12)
┌────────────┬─────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬───────────┐
│ THE_PK_KEY ┆ SECTION ┆ DISTRICT  ┆ DISTRICT_ ┆ … ┆ #MALE_REG ┆ #FEMALE_R ┆ #MALE_VOT ┆ #FEMALE_V │
│ ---        ┆ ---     ┆ ---       ┆ CD        ┆   ┆ ISTERED   ┆ EGISTERED ┆ ERS       ┆ OTERS     │
│ str        ┆ i64     ┆ str       ┆ ---       ┆   ┆ ---       ┆ ---       ┆ ---       ┆ ---       │
│            ┆         ┆           ┆ i64       ┆   ┆ i64       ┆ i64       ┆ i64       ┆ i64       │
╞════════════╪═════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪═══════════╡
│ 160_San    ┆ 160     ┆ San       ┆ 4         ┆ … ┆ 394       ┆ 418       ┆ 296       ┆ 319       │
│ Faustino_E ┆         ┆ Faustino  ┆           ┆   ┆           ┆           ┆           ┆           │
│ uropee     ┆         ┆           ┆           ┆   ┆           ┆           ┆           ┆           │
│ 161_San    ┆ 161     ┆ San       ┆ 4         ┆ … ┆ 281       ┆ 309       ┆ 188       ┆ 198       │
│ Faustino_E ┆         ┆ Faustino  ┆           ┆   ┆           ┆           ┆           ┆           │
│ uropee     ┆         ┆           ┆           ┆   ┆           ┆           ┆           ┆           │
│ 164_San    ┆ 164     ┆ San       ┆ null      ┆ … ┆ 383       ┆ 421       ┆ 279       ┆ 303       │
│ Faustino_E ┆         ┆ Faustino  ┆           ┆   ┆           ┆           ┆           ┆           │
│ uropee     ┆         ┆           ┆           ┆   ┆           ┆           ┆           ┆           │
│ 166_San    ┆ 166     ┆ San       ┆ 4         ┆ … ┆ 357       ┆ 327       ┆ 237       ┆ 229       │
│ Faustino_E ┆         ┆ Faustino  ┆           ┆   ┆           ┆           ┆           ┆           │
│ uropee     ┆         ┆           ┆           ┆   ┆           ┆           ┆           ┆           │
│ null       ┆ 167     ┆ San       ┆ 4         ┆ … ┆ 395       ┆ 434       ┆ 296       ┆ 325       │
│            ┆         ┆ Faustino  ┆           ┆   ┆           ┆           ┆           ┆           │
│ …          ┆ …       ┆ …         ┆ …         ┆ … ┆ …         ┆ …         ┆ …         ┆ …         │
│ 154_San    ┆ 154     ┆ San       ┆ 4         ┆ … ┆ 340       ┆ 383       ┆ 249       ┆ 280       │
│ Faustino_E ┆         ┆ Faustino  ┆           ┆   ┆           ┆           ┆           ┆           │
│ uropee     ┆         ┆           ┆           ┆   ┆           ┆           ┆           ┆           │
│ 156_San    ┆ 156     ┆ San       ┆ 4         ┆ … ┆ 373       ┆ 394       ┆ 262       ┆ 273       │
│ Faustino_E ┆         ┆ Faustino  ┆           ┆   ┆           ┆           ┆           ┆           │
│ uropee     ┆         ┆           ┆           ┆   ┆           ┆           ┆           ┆           │
│ 157_San    ┆ 157     ┆ San       ┆ 4         ┆ … ┆ 359       ┆ 374       ┆ 256       ┆ 253       │
│ Faustino_E ┆         ┆ Faustino  ┆           ┆   ┆           ┆           ┆           ┆           │
│ uropee     ┆         ┆           ┆           ┆   ┆           ┆           ┆           ┆           │
│ 158_San    ┆ 158     ┆ San       ┆ null      ┆ … ┆ 372       ┆ 429       ┆ 279       ┆ 313       │
│ Faustino_E ┆         ┆ Faustino  ┆           ┆   ┆           ┆           ┆           ┆           │
│ uropee     ┆         ┆           ┆           ┆   ┆           ┆           ┆           ┆           │
│ 159_San    ┆ 159     ┆ San       ┆ 4         ┆ … ┆ 364       ┆ 408       ┆ 272       ┆ 292       │
│ Faustino_E ┆         ┆ Faustino  ┆           ┆   ┆           ┆           ┆           ┆           │
│ uropee     ┆         ┆           ┆           ┆   ┆           ┆           ┆           ┆           │
└────────────┴─────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴───────────┘

## Multi-Column JOIN Search - Combination of single-JOIN searches

In many cases, a single column doesn't identify every record of a dataset, and a combination of different attributes is thus required.

Suppose that we do not have anymore the "THE_KEY" column.

In [14]:
qdf = qdf.drop("THE_PK_KEY")
qdf.head()

shape: (5, 26)
┌─────────┬──────────┬─────────────┬───────────┬───┬────────┬──────┬────────────┬───────┐
│ SECTION ┆ DISTRICT ┆ DISTRICT_CD ┆ DATA_TYPE ┆ … ┆ #VALID ┆ FORM ┆ #NOT VALID ┆ #NULL │
│ ---     ┆ ---      ┆ ---         ┆ ---       ┆   ┆ ---    ┆ ---  ┆ ---        ┆ ---   │
│ i64     ┆ str      ┆ i64         ┆ str       ┆   ┆ i64    ┆ str  ┆ i64        ┆ i64   │
╞═════════╪══════════╪═════════════╪═══════════╪═══╪════════╪══════╪════════════╪═══════╡
│ 1       ┆ Centro   ┆ 1           ┆ Liste     ┆ … ┆ 525    ┆ E24  ┆ 8          ┆ 2     │
│ 2       ┆ Centro   ┆ 1           ┆ Liste     ┆ … ┆ 431    ┆ E24  ┆ 13         ┆ 10    │
│ 5       ┆ Centro   ┆ 1           ┆ Liste     ┆ … ┆ 505    ┆ E24  ┆ 7          ┆ 4     │
│ 7       ┆ Centro   ┆ 1           ┆ Liste     ┆ … ┆ 584    ┆ E24  ┆ 12         ┆ 8     │
│ 8       ┆ Centro   ┆ 1           ┆ Liste     ┆ … ┆ 392    ┆ E24  ┆ 6          ┆ 2     │
└─────────┴──────────┴─────────────┴───────────┴───┴────────┴──────┴────────────┴───────┘

How can we search joinable tables on "SECTION", "DISTRICT_CD", and "ELECTION" columns at the same time?

To identify joinable tables on multiple columns, can we run several single-column searches? Is this a good option?

In [15]:
column = qdf.get_column('SECTION').drop_nulls().to_list()
results_section = indexer.single_column_join_search(column, k=10)

In [16]:
column = qdf.get_column('DISTRICT').drop_nulls().to_list()
results_district = indexer.single_column_join_search(column, k=10)

In [17]:
column = qdf.get_column('ELECTION').drop_nulls().to_list()
results_election = indexer.single_column_join_search(column, k=10)

In [18]:
from collections import defaultdict


aggregation = defaultdict(int)

for results in [results_section, results_district, results_election]:
    for table, _, _ in results:
        aggregation[table] += 1

In [19]:
results = list(sorted(list(aggregation.items()), key=lambda r: r[1], reverse=True))

# select the top-k
results = results[:10]

print(tabulate(results, ['dataset', 'occurrences']))

dataset                                                                      occurrences
-------------------------------------------------------------------------  -------------
Affluenze-e-risultati-elettorali-delle-elezioni-europee-2024                           3
Risultati-di-lista-delle-elezioni-amministrative-del-2024                              2
Affluenze-e-risultati-elettorali-delle-elezioni-amministrative-2024.cpy-0              1
Pratiche-edilizie-anni-dal-2000-ad-oggi                                                1
Risultati-di-lista-delle-elezioni-regionali-del-2024.unpivot.cpy-0                     1
Affluenze-delle-elezioni-amministrative-2019                                           1
Risultati-di-lista-delle-elezioni-europee-del-2024.cpy-0                               1
Risultati-delle-elezioni-europee-2019.unpivot                                          1
File-in-formato-csv                                                                    1
Risultati-di-lista-delle-elezioni-regionali-del-2020                                   1

By combining results from different single-column searches we have some drawbacks in the end: 

- the order isn't always the same, 
- can be costly, if we need to run it on a high number of different columns,
- the alignment of the rows isn't guaranteed.

## Multi-Column JOIN Search - MATE algorithm

Instead, we can use a **multi-column search** approach. 

This is based on MATE (Multi-Attribute Table Extraction) algorithm, which allows us to search n-ary joins without any
other intermediate step.

In [8]:
table = qdf.select(['SECTION', 'DISTRICT', 'ELECTION']).rows()

print(tabulate(table[:10]))

--  ------  -------
 1  Centro  Europee
 2  Centro  Europee
 5  Centro  Europee
 7  Centro  Europee
 8  Centro  Europee
 9  Centro  Europee
10  Centro  Europee
11  Centro  Europee
12  Centro  Europee
14  Centro  Europee
--  ------  -------

In [ ]:
mc_results = indexer.multi_column_join_search(table, 10, verbose=True)

Preprocessing posting lists    : 100%|████████████████████████████████████████| 56126/56126 [00:00<00:00, 123524.94it/s]
Checking candidate tables      : 100%|██████████████████████████████████████████████████| 28/28 [00:00<00:00, 64.73it/s]
Evaluating candidate table rows: 100%|█████████████████████████████████████████| 28535/28535 [00:00<00:00, 97179.06it/s]

In [17]:
print(f"Query table: {query_table_name}\n")
print(tabulate(mc_results, headers=['dataset', 'columns', 'join_score']))

Query table: Risultati-di-lista-delle-elezioni-europee-del-2024.cpy-0.csv

dataset                                                           columns      join_score
----------------------------------------------------------------  ---------  ------------
Risultati-delle-elezioni-europee-2019.unpivot.cpy-0               [0, 1, 3]          2423
Risultati-delle-elezioni-europee-2019.unpivot.cpy-1               [0, 1, 3]          2190
Risultati-delle-elezioni-europee-2019.unpivot                     [0, 1, 3]          2736
Risultati-delle-elezioni-europee-2009.unpivot                     [0, 1, 3]          2235
Risultati-delle-elezioni-europee-anno-2014.unpivot                [0, 1, 3]          2235
Risultati-delle-elezioni-europee-anno-2014.unpivot.cpy-0          [0, 1, 3]          1795
Risultati-di-lista-delle-elezioni-europee-del-2024.unpivot        [0, 1, 3]          1976
Risultati-delle-elezioni-europee-anno-2014.unpivot.cpy-1          [0, 1, 3]          1795
Risultati-delle-elezioni-europee-2009.unpivot.cpy-1               [0, 1, 3]          1795
Risultati-di-lista-delle-elezioni-europee-del-2024.unpivot.cpy-1  [0, 1, 3]          1583

The order of the columns **doesn't affect** the final results, but might impact the efficiency (see section 6.1 of MATE paper if you are interested).

The final order in the top-K might slightly change, but overall the top-K tables should be the same.

We can swap the columns used before:

In [18]:
table = qdf.select(['DISTRICT', 'SECTION', 'ELECTION']).rows()
print(tabulate(table[:5]))

------  -  -------
Centro  1  Europee
Centro  2  Europee
Centro  5  Europee
Centro  7  Europee
Centro  8  Europee
------  -  -------

In [19]:
mc_results_v2 = indexer.multi_column_join_search(table, 10, verbose=True)

Preprocessing posting lists    : 100%|████████████████████████████████████████| 56126/56126 [00:00<00:00, 128493.45it/s]
Checking candidate tables      : 100%|██████████████████████████████████████████████████| 28/28 [00:01<00:00, 17.59it/s]
Evaluating candidate table rows: 100%|██████████████████████████████████████| 799177/799177 [00:03<00:00, 232971.70it/s]

In [20]:
# the results are the same obtained above
print(tabulate(mc_results_v2, headers=['dataset', 'columns', 'join_score']))

dataset                                                           columns      join_score
----------------------------------------------------------------  ---------  ------------
Risultati-delle-elezioni-europee-2019.unpivot.cpy-0               [1, 0, 3]          3505
Risultati-di-lista-delle-elezioni-europee-del-2024.unpivot        [1, 0, 3]          3249
Risultati-delle-elezioni-europee-2019.unpivot                     [1, 0, 3]          4248
Risultati-delle-elezioni-europee-2009.unpivot                     [1, 0, 3]          3545
Risultati-delle-elezioni-europee-anno-2014.unpivot                [1, 0, 3]          3545
Risultati-delle-elezioni-europee-2009.unpivot.cpy-1               [1, 0, 3]          2652
Risultati-delle-elezioni-europee-2019.unpivot.cpy-1               [1, 0, 3]          3153
Risultati-delle-elezioni-europee-anno-2014.unpivot.cpy-1          [1, 0, 3]          2631
Risultati-delle-elezioni-europee-anno-2014.unpivot.cpy-0          [1, 0, 3]          2628
Risultati-di-lista-delle-elezioni-europee-del-2024.unpivot.cpy-1  [1, 0, 3]          2385

In [21]:
tables_from_run_1 = {r[0] for r in mc_results}
tables_from_run_2 = {r[0] for r in mc_results_v2}

len(tables_from_run_1.intersection(tables_from_run_2)), tables_from_run_1.difference(tables_from_run_2), tables_from_run_2.difference(tables_from_run_1)

(10, set(), set())

We can do another test with a different combination of the same three columns:

In [22]:
qdf.get_column('ELECTION').unique()

shape: (1,)
Series: 'ELECTION' [str]
[
	"Europee"
]

In [23]:
table = qdf.select(['ELECTION', 'DISTRICT', 'SECTION']).rows()
print(tabulate(table[:3]))

-------  ------  -
Europee  Centro  1
Europee  Centro  2
Europee  Centro  5
-------  ------  -

In [26]:
mc_results_v3 = indexer.multi_column_join_search(table, 10, verbose=True)

Preprocessing posting lists    : 100%|████████████████████████████████████████| 56126/56126 [00:00<00:00, 145439.66it/s]
Checking candidate tables      : 100%|██████████████████████████████████████████████████| 28/28 [00:03<00:00,  8.87it/s]
Evaluating candidate table rows: 100%|███████████████████████████████████████| 799238/799238 [00:09<00:00, 81812.11it/s]

In [27]:
tables_from_run_1 = {r[0] for r in mc_results}
tables_from_run_2 = {r[0] for r in mc_results_v2}
tables_from_run_3 = {r[0] for r in mc_results_v3}

len(tables_from_run_1.intersection(tables_from_run_2).intersection(tables_from_run_3))

10